### ISSUE TITLE
Kind of roadmap.

### ISSUE THREAD

**Issue by aberezkin** [moroshko/react-autosuggest#734]
This is an issue to track progress on things I think we need to do in this repo. 

- [ ] Merge `react-autosuggest` in this repo to make it easier to maintain both libs.
- [ ] Integrate [renovate](https://renovate.whitesourcesoftware.com/) to keep dependencies up to date.
- [ ] Implement headless UI to solve problems with custom styling.
- [ ] Rewrite test with something modern (jest, react-testing-library, cypress).

If you have ideas on other major improvements, feel free to comment or open an issue.

**Comment by bndby** [comment]
Add typescript definitions

**Comment by aberezkin** [comment]
Good idea @bndby, thank you

**Comment by SFJonathanChen** [comment]
Going through existing PRs and merging them in if there are no issues or prodding PR authors if there are?

**Comment by aberezkin** [comment]
@SFJonathanChen, I'm doing this anyway on my spare time.

**Comment by fatso83** [comment]
There is still an open call for additional maintainers in the README, so if someone really thinks things are taking too long, there are vacant positions, @SFJonathanChen :-)
